### ISSUE TITLE
have plan to lua-compat-5.3?

### ISSUE THREAD

**Issue by zhaozg** [keplerproject/lua-compat-5.2#17]
have plan to lua-compat-5.3?

**Comment by daurnimator** [comment]
5.3 seems to be getting very close to release, I'm wondering if we want to start a compat-5.3 project now? one of the first things I'd like is `lua_rotate`

**Comment by zhaozg** [comment]
Another repos? or continues from here?

**Comment by hishamhm** [comment]
Right now I don't have personal plans to do it, but if someone wants to, feel free to use the `lua-compat-5.3` name.

> One interesting question is: Should lua-compat-5.3 provide a Lua 5.3 API/environment for Lua 5.2 only, or for Lua 5.1 as well (like an extension of lua-compat-52, except that we can actually remove some stuff that's no longer in Lua 5.3)?

@siffiejoe, I think it's up to who wants to implement it. :)

**Comment by siffiejoe** [comment]
@hishamhm: Do you want to create the `lua-compat-53` repository here, or should I open one at my place? (I'd prefer here, because many C API functions are taken from the `lua-compat-52` project anyway.)

**Comment by hishamhm** [comment]
@siffiejoe, maybe it's time to move this over to keplerproject and create the new one there too?

**Comment by siffiejoe** [comment]
Sounds good!

**Comment by hishamhm** [comment]
@siffiejoe Aaaand... we're moved!

**Comment by hishamhm** [comment]
I wonder if there's a way to create keplerproject/lua-compat-5.3 such that it is "forked from keplerproject/lua-compat-5.2"... anyway, is keeping it as two separate projects too messy? lua-compat-5.2 is basically stable and "done" by now, right?

**Comment by siffiejoe** [comment]
> I wonder if there's a way to create keplerproject/lua-compat-5.3 such that it is "forked from keplerproject/lua-compat-5.2"... anyway, is keeping it as two separate projects too messy? 

I think you could create a new Github project, add the `lua-compat-52` repository as a remote via the command line, and pull everything over. However, I currently have working code only for the C-API, not for the Lua side, so we would import a lot of cruft for now. Also, my code is based on the `linker-tricks` branch, not `master`. So a clean repository would be fine as well -- we could just point to the older project using the readme.

> lua-compat-5.2 is basically stable and "done" by now, right?

I think so. That's why I didn't bother to merge the `linker-tricks` branch: Nobody complained about linker errors, and there are users actively using the current code base. I also think that most people who start new projects now will try to support Lua 5.3, so `lua-compat-52` is basically in maintainance-mode ...

**Comment by hishamhm** [comment]
Great, let's go with a clean repository then. I'll create one under keplerproject.

**Comment by hishamhm** [comment]
Done!
https://github.com/keplerproject/lua-compat-5.3
@siffiejoe, we're both in "Team lua-compat", set with Admin status, so you can add people to the projects.

**Comment by daurnimator** [comment]
awesome. :)

Should we file issues on a function per function basis over there? or does someone have it in them to do an initial sprint?
