### ISSUE TITLE
luaL_Stream implementation is incomplete or undocumented for 5.1

### ISSUE THREAD

**Issue by rrthomas** [keplerproject/lua-compat-5.2#22]
See https://github.com/luaposix/luaposix/commit/a83c89b8aaf530d43169bf5927db5b51a4dfd7e4#commitcomment-9978862 : it seems that either the implementation is incomplete for 5.1, or, if it's impossible to make it work automatically, the extra requirements on library code need to be documented.

**Comment by siffiejoe** [comment]
The specific issue was discussed in #10. I see no way to make code that uses `luaL_Stream` work exactly the same on Lua 5.1 and 5.2 without extra manual handling of 5.1 (even more so when LuaJIT is involved).
So we probably need some form of documentation where the not-100%-compatible functions/types and their limitations are listed. Should we use the GitHub wiki (one page per issue and one overview page), or an extra documentation file in the repository (I think the main readme is not the right place for this)? This also concerns Compat-5.3. Suggestions?

**Comment by rrthomas** [comment]
For this case, a link from the README to the issue would be a start.

In general, I agree that the wiki is a good place (because there will probably be improvements to be made and problems to be noted over time), linked from a list of problematic APIs in the README.

**Comment by siffiejoe** [comment]
@hishamhm: Any preferences about this? If not I'll start the wiki pages (there has been some new development regarding `luaL_Stream` and LuaJIT).

**Comment by hishamhm** [comment]
For docs that are meant to be installed with the rock, a doc/ subdir makes it easier. But a wiki is also fine, I'm using it for LuaRocks.

**Comment by siffiejoe** [comment]
The `luaL_Stream` type has been removed from the compatibility C API (see #10). Nonetheless, I have started a GitHub wiki to document any gotchas that I'm aware of (adding links from the main readme). As an experiment I've also written an small Lua script to generate a single HTML file from the wiki pages (as long as they are regular markdown without GitHub flavor), and committed this HTML file in a branch of the wiki repository. Using git submodules that branch can be linked into the main repository as a `doc` subdirectory. That works rather nicely, because in the GitHub web UI you are forwarded to the actual wiki, while `luarocks doc compat52` finds the generated HTML file instead. You can see the results of that experiment at the `wikidoc` branch. Sadly, LuaRocks doesn't use the `--recursive` flag when cloning (see keplerproject/luarocks#106 and keplerproject/luarocks#169). So I'm considering to use subtrees (still reading up on them, but I suspect that we'll lose the live link to the wiki pages), or waiting for LuaRocks NextGen (which hopefully will clone recursively).

**Comment by rrthomas** [comment]
@sifflejoe, thanks, this is exactly what I would've wanted first time round, and I'm sure it will save other developers time in future!
